### PR TITLE
fix: Refactor id processor to always use toString

### PR DESCRIPTION
**Pull request by wtrocki**
fix for https://github.com/aerogear/offix/issues/74

Waiting for more info to write integration tests.

### CODE REVIEW

**Comment by darahayes** [comment]
@wtrocki looks like your editor did some auto formatting. Was that intentional?

**Comment by wtrocki** [comment]
@darahayes - Yes. Some of the files we have are not formatted properly to avoid problems with backporting changes I have formatted it (sorry for readability)

**Comment by darahayes** [comment]
@wtrocki @StephenCoady it would be nice to have some unit tests for the `execute` function here. From what I can see it's deterministic on the inputs provided so it should be easy to unit test. What would you think about creating an issue and getting @MStokluska to have a look?

**Comment by wtrocki** [comment]
@StephenCoady Quick review.

**Pull request merged**
