### PR TITLE
Update Apollo GraphQL packages

### PR DESCRIPTION
**Pull request by wtrocki**
Working on fix for #104

### CODE REVIEW

**Comment by wtrocki** [comment]
@StephenCoady I think that generally having merged types with Apollo will cause a lot of problems over time. My first thought is to separate them and operate on plain Apollo options and Separate cache helper options. 

Cache helper options are strongly typed with generics that are not used in MutationHelperOptions extensions. WDYT?

**Comment by StephenCoady** [comment]
So you mean just rely fully on plain mutate and supply the `update` function separately using a new endpoint? So we need to split and use `optimisticResponse` and `update` individually then. If you think that will decrease problems in the future with being tied to Apollo's API then I am all for it.

**Comment by wtrocki** [comment]
I think we still decorate their original object but we do not supply additional parameters with it. The fact that we supply all additional parameters means that we need to conform to the generic interface - which causes some issues.

**Comment by StephenCoady** [comment]
OK, sounds fine to me. let me throw that into a pr now

**Comment by StephenCoady** [comment]
@wtrocki see here: https://github.com/aerogear/offix/pull/106

I broke the merged type - do you think an intersection is enough for what you mean? I know top level is still the same but this way they can move on independently.

**Comment by wtrocki** [comment]
Closing

**Pull request closed without merging**
