### PR TITLE
fix: add default opType to mutation options

### PR DESCRIPTION
**Pull request by StephenCoady**
### Description

This is a fix for https://github.com/aerogear/offix/issues/111

##### Checklist

- [ ] `npm test` passes
- [ ] `npm run build` works
- [ ] tests are included
- [ ] documentation is changed or added

### CODE REVIEW

**Comment by wtrocki** [comment]
Ah.. but this requires undefined to be passed. Kinda defeats the purpose.

**Comment by StephenCoady** [comment]
ah. theres no way to do it then without breaking the api really.

**Comment by wtrocki** [comment]
yeah, rule of thumb is to add things at the end with defaults or use objects if possible. Objects are cool for typescript but hard for js so they should be used sporadically.

**Comment by StephenCoady** [comment]
@wtrocki if we want the updateQuery to be optional and to provide a default for the opType we don't have an option but to use objects really. wdyt?

**Comment by wtrocki** [comment]
Generally rule of thumb from clean code is to never have more than 3 inputs to function. If we do more then this function becomes unmanagable. It is even worse if the function becomes an public api. Objects are probably for the best

**Comment by StephenCoady** [comment]
@wtrocki I have made the changes. I know you are hesitant for a breaking change but it is here if you want it. I will leave it up to you whether we merge this now or after.

**Comment by wtrocki** [comment]
>  know you are hesitant for a breaking change 

Absolutely not. We cannot avoid breaking here

**Comment by StephenCoady** [comment]
Closing this as these changes are included in https://github.com/aerogear/offix/pull/117

**Pull request closed without merging**
