### PR TITLE
Next rebased

### PR DESCRIPTION
**Pull request by wtrocki**
Hi guys.. This PR contains only datastore changes that should be landing on master.
I would look for quick review (especially @Eunovo) to see if we can merge this and then continue creating PR's against master.

### CODE REVIEW

**Comment by wtrocki** [comment]
Actually - @Eunovo Since we are leaving the offix generic untouched we need separate app..This means that we need to - rename sample app on this branch to react-datastore and copy original app from master

**Comment by kingsleyzissou** [comment]
@wtrocki @Eunovo  I'll sort the app thing out quickly and add to PR

**Comment by wtrocki** [comment]
thx.

**Comment by Eunovo** [comment]
@wtrocki  please merge #576 before merging this PR

**Comment by wtrocki** [comment]
Yes. Merging now!

**Pull request merged**
