### PR TITLE
Use enums for events and other quick fixes closes #569 #573

### LINKED ISSUE #569: DataStore.createModel instead of create

### PR DESCRIPTION
**Pull request by Eunovo**
I have replaced EventTypes with DatabaseEvents enums and rename DataStore.create to DataStore.createModel

### CODE REVIEW

**Comment by wtrocki** [comment]
This will conflict badly with @kingsleyzissou work

**Comment by wtrocki** [comment]
@kingsleyzissou Can you include this as well in changes?

**Comment by wtrocki** [comment]
Merged. Ignore previous comment

**Comment by wtrocki** [comment]
@Eunovo Suggested action here.

```
git reset --soft head~2
git stash 
git checkout master
git pull origin master
git stash pop
git checkout -b newbranch
git commit -m"new changes"
git push origin newbranch
```

**Comment by kingsleyzissou** [comment]
@wtrocki sorry just to clarify, should I be adding this into the TypeScript app?

**Comment by wtrocki** [comment]
Eunovo works on this now

**Pull request closed without merging**
