### PR TITLE
Bundle size

### PR DESCRIPTION
**Pull request by kingsleyzissou**
### Description

- Add CI stage for bundle sizes
- Check can be run from root level and from package level
- at pacakage level, `size:why` script is available to view package dependencies (see screenshot)

image

##### Checklist

- [x] `npm test` passes
- [x] `npm run build` works
- [ ] tests are included
- [ ] documentation is changed or added

### CODE REVIEW

**Comment by wtrocki** [comment]
I can see why persist is taking so much. It is very small library so it might be possible that it incorporates some extra packages from Apollo that are not needed. On the other hand we can also generate esm of our stuff as this will put it's size by half. 

I think this will look much simpler if we create single dist over the apollo package and dist with apollo package and then compare it to the apollo package itself. Our packages are in non minified form so it is artificaly large

**Comment by kingsleyzissou** [comment]
@wtrocki the package that we use minifies and gzips our packages. The screenshot there is just from all the dependencies in the offix-client package.

image

This is from bundlephobia that shows something similar to the initial screenshot:

image

**Comment by wtrocki** [comment]
That is really good! I would call it small in my standards

**Comment by kingsleyzissou** [comment]
@darahayes I'll do that now quick

**Pull request merged**
