### PR TITLE
Update example to use offix boost

### PR DESCRIPTION
**Pull request by wtrocki**
Still WIP. Using this to reproduce issues and hoping to fix one :D

### CODE REVIEW

**Comment by wtrocki** [comment]
This is WIP, but want to know about what you think of us using offix boost in example

**Comment by wtrocki** [comment]
Screenshot 2020-06-25 at 11 55 43

Some errors happening with sample app - No matter if this branch or master

**Comment by kingsleyzissou** [comment]
Yeah we can use offix-boost, no problem for me there.

The error is a bit strange. Not getting it on my end. But will double check

**Comment by wtrocki** [comment]
Update. Offix releases have some code that is not on the master.

onStatusChangeListener is still there but it is no longer supported. 
React-offix-hooks package:
Screenshot 2020-06-25 at 12 29 30

**Comment by wtrocki** [comment]
Used this PR to check file integration. We do not have file support in graphql-serve so we cannot apply this.

**Pull request closed without merging**
