### PR TITLE
Re-factored tests

### PR DESCRIPTION
**Pull request by dewstend**
### Description

Like mentioned in #192, I migrated the integration tests in `offix-client` to TypeScript and codeshifted mocha to Jest, some TypeScript type-checking is required, I'm sending this PR for suggestions and edits.

### CODE REVIEW

**Comment by darahayes** [comment]
@dewstend Thanks so much for this amazing contribution! I'm really happy with the changes. The build is failing due to tonnes of linter errors which are not really your fault. We obviously wrote that JS code with different standards to how we write out TS code 😅

Fixing the lint issues will bring tonnes of extra changes to all those files I think we should do it. You can run `npm run lint-fix` and push those additional changes and we will take it from there!

**Comment by wtrocki** [comment]
This is the most amazing change we received in entire hacktoberfest. Thank you so much. Do you mind to be added to our contributor list on our webpage?

**Comment by dewstend** [comment]
@wtrocki, I don't mind being added to the contributors list! I represent @NovaHelm, I develop there.

I already linted the files, @darahayes, it was a bit unintuitive for me since you use TSLint and npm scripts.

I see there are .vscode files, I also use Code, and I usually have ESLint files and its plugin for auto-lint/format on save.
Also, as stated in palantir/tslint#4534, TSLint will be deprecated in favour of ESLint and [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint).

**Comment by darahayes** [comment]
Hey @dewstend I still see some linter errors in the build. Would you be able to fix those so we can proceed with this PR?

> I see there are .vscode files, I also use Code, and I usually have ESLint files and its plugin for auto-lint/format on save.

This is a completely valid approach, but our team decided to implement the linting process as an npm script that can be checked in CI.

> Also, as stated in palantir/tslint#4534, TSLint will be deprecated in favour of ESLint and typescript-eslint.

Thanks a lot for this info. Offix started before TSLint became deprecated. I think we can solve that as a separate issue/PR if you are interested! As for this PR, I think we are good to go once the build is passing!

**Comment by dewstend** [comment]
@darahayes I've tried troubleshooting some of the errors, I can't fix them with auto-linting, most errors are inherent to how code was written in JavaScript, when I ported to TypeScript automatically, I fixed what I could, other errors are specific to the design, maybe?

**Comment by wtrocki** [comment]
Thank you so much. Our team will take this over from now and merge PR as soon as possible

**Comment by darahayes** [comment]
Working on getting this merged right now

**Comment by darahayes** [comment]
@dewstend I have cherry picked your commits into #223 which includes some extra fixes. Once that PR is passing I will merge that one and close this one. Because you authored those commits you will still be added as a contributor to the project. Thanks for your work!

**Comment by darahayes** [comment]
@dewstend your changes have landed in https://github.com/aerogear/offix/commit/f5f501c34e0fcaab2a4e83e6a1516bce5dd405eb

Thanks for your contribution!

**Pull request closed without merging**
