### PR TITLE
Push Update and Delete operations to server

### PR DESCRIPTION
**Pull request by Eunovo**
### Description

Push Update and Delete operations to the server. Since update and delete are executed in batches, each affected row is pushed as a single operation to the server.

##### Checklist

- [x] `npm test` passes
- [x] `npm run build` works
- [x] tests are included

### CODE REVIEW

**Comment by Eunovo** [comment]
@wtrocki  @kingsleyzissou  Update op replication fails when tested in example app. It seems there seems to be an error with the id

**Comment by kingsleyzissou** [comment]
Okay will have a look at this. Which id is being sent? Is it the uuid generates by the data store or the server generated Id?

**Comment by Eunovo** [comment]
The uuid generated by the datastore

**Comment by wtrocki** [comment]
@Eunovo Can we fix build and merge this. 
I would love to rebase the next branch and remove some of the non datastore changes.

**Pull request merged**
